language: haskell
ghc:
  #- '7.10'  #travis currently doesn't have GHC 7.10; need to install manually if we want to test with it
  - 7.8
  - 7.6
  - 7.4
script:
  - cabal configure --enable-tests && cabal build #configure and build with tests but don't run tests
notifications:
  email: false